# Checkov suppressions for accepted risks and false positives
skip-check:
  # Cross-region replication - not needed for single-region portfolio
  - CKV_AWS_144  # Alerts #19, #18
  
  # KMS encryption - AES256 sufficient for logs and public content
  - CKV_AWS_145  # Alerts #12, #11
  
  # S3 event notifications - not needed for static site
  - CKV2_AWS_62  # Alerts #16, #15
  
  # CloudFront origin failover - single origin by design
  - CKV_AWS_310  # Alert #10
  
  # CloudFront TLS version - already using TLS 1.2+ (false positive)
  - CKV_AWS_174  # Alert #9
  
  # CloudFront geo restrictions - portfolio site, global access needed
  - CKV_AWS_374  # Alert #8
  
  # CloudFront custom SSL - using default CloudFront cert is fine
  - CKV2_AWS_42  # Alert #17
  
  # CloudFront WAF Log4j rule - managed by AWS WAF, not our responsibility
  - CKV2_AWS_47  # Alert #14
  
  # WAF logging - only needed when WAF is enabled (conditional)
  - CKV2_AWS_31  # Alert #13
